export const productList = [
    {
        id: '1',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2030A',
        price : 1299,
        discountedPrice: 700,
        discountPercent: 46,
        category : 'senior boys',
        imageUrl:'/products/product1.jpg',
        images:['/products/product1.jpg','/products/product1.jpg','/products/product1.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '2',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2031A',
        price : 299,
        discountedPrice: 224,
        discountPercent: 25,
        category : 'senior boys',
        imageUrl:'/products/product2.jpg',
        images:['/products/product2.jpg','/products/product2.jpg','/products/product2.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '3',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2029A',
        price : 299,
        discountedPrice: 254,
        discountPercent: 15,
        category : 'senior boys',
        imageUrl:'/products/product3.jpg',
        images:['/products/product3.jpg','/products/product3.jpg','/products/product3.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '4',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2028A',
        price : 299,
        discountedPrice: 206,
        discountPercent: 31,
        category : 'senior boys',
        imageUrl:'/products/product4.jpg',
        images:['/products/product4.jpg','/products/product4.jpg','/products/product4.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '5',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2027A',
        price : 299,
        discountedPrice: 269,
        discountPercent: 10,
        category : 'senior boys',
        imageUrl:'/products/product5.jpg',
        images:['/products/product5.jpg','/products/product5.jpg','/products/product5.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '6',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2032A',
        price : 299,
        discountedPrice: 176,
        discountPercent: 41,
        category : 'senior boys',
        imageUrl:'/products/product6.jpg',
        images:['/products/product6.jpg','/products/product6.jpg','/products/product6.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '7',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2067A',
        price : 299,
        discountedPrice: 259,
        discountPercent: 13,
        category : 'senior boys',
        imageUrl:'/products/product7.jpg',
        images:['/products/product7.jpg','/products/product7.jpg','/products/product7.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '8',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2025A',
        price : 299,
        discountedPrice: 224,
        discountPercent: 25,
        category : 'senior boys',
        imageUrl:'/products/product8.jpg',
        images:['/products/product8.jpg','/products/product8.jpg','/products/product8.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '9',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2024A',
        price : 299,
        discountedPrice: 188,
        discountPercent: 37,
        category : 'senior boys',
        imageUrl:'/products/product9.jpg',
        images:['/products/product9.jpg','/products/product9.jpg','/products/product9.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '10',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2023A',
        price : 299,
        discountedPrice: 269,
        discountPercent: 10,
        category : 'senior boys',
        imageUrl:'/products/product10.jpg',
        images:['/products/product10.jpg','/products/product10.jpg','/products/product10.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '11',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2040A',
        price : 299,
        discountedPrice: 206,
        discountPercent: 31,
        category : 'senior boys',
        imageUrl:'/products/product11.jpg',
        images:['/products/product11.jpg','/products/product11.jpg','/products/product11.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
    {
        id: '12',
        title:'T-Shirt',
        description:'H/S CHEST PRINT TEES',
        size: ['9-10Y','11-12Y','13-14Y','15-16Y'],
        skuId : 'BT-2039A',
        price : 299,
        discountedPrice: 254,
        discountPercent: 15,
        category : 'senior boys',
        imageUrl:'/products/product12.jpg',
        images:['/products/product12.jpg','/products/product12.jpg','/products/product12.jpg'],
        variations:'simple t-shirt',
        tags:['t-shirt','kids','child','genZ','trend']
    },
]
  