import mongoose from "mongoose";

const productSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: String,
  size: [String],
  skuId: { type: String, unique: true },
  price: Number,
  discountedPrice: Number,
  discountPercent: Number,
  category: String,
  subCategory: String,
  gender: String,
  ageGroup: String,
  imageUrl: String,
  images: [String],
  variations: String,
  tags: [String],
  fabric: String,
  material: String,
  washCare: String,
  whatsIncluded: String,
  styleCode: String,
  countryOfOrigin: String,
  sizeRange: String,
  fitType: String,
  length: String,
  chestWaist: String,
  shoulderWidth: String,
  sleeveLength: String,
  neckType: String,
  closureType: String,
  fabricComposition: String,
  fabricType: String,
  gsm: String,
  breathability: String,
  softness: String,
  skinFriendly: String,
  seasonSuitability: String,
  transparent: String,
  patternPrint: String,
  printPlacement: String,
  printTechnique: String
}, { timestamps: true });

const Product = mongoose.model("Product", productSchema);
export default Product;
